api/urls.py
from django.urls import path, include
from api import views

app_name = 'api'
urlpatterns = [
    path("first_page/", views.first_page, name='first_page'),
    path("wen/", views.wen, name='wen'),
    path("register/", views.register, name='register'),
    path("modify/", views.modify),
]

hjs_cmfz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include("main.urls")),
    path('banner/', include("banner.urls")),
    path('user/', include("user.urls")),
    path('article/', include("article.urls")),
    path('api/', include("api.urls")),
    path('rabc/', include("rabc.urls")),
]

main/urls.py
from django.urls import path
from main import views
urlpatterns = [
    path('main/', views.main, name='main'),
    path('login/', views.login_form, name='login'),
    path('get_code/', views.get_code, name='get_code'),
    path('check_user/', views.check_user, name='check_user'),
]

rabc/urls.py
from django.urls import path, include
from rabc import views
app_name = 'rbac'
urlpatterns = [
    path("login/", views.login,name='login'),
    path("check_user/", views.check_user,name='check_user'),

]

main/models.py
from django.db import models


# Create your models here.

class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class TAdmin(models.Model):
    username = models.CharField(max_length=50, blank=True, null=True)
    password = models.CharField(max_length=50, blank=True, null=True)
    salt = models.CharField(max_length=20, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_admin'


class TAlbum(models.Model):
    album_title = models.CharField(max_length=50, blank=True, null=True)
    thumbnail_url = models.CharField(max_length=100, blank=True, null=True)
    author = models.CharField(max_length=50, blank=True, null=True)
    bordcaster = models.CharField(max_length=50, blank=True, null=True)
    chapter_num = models.IntegerField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    publish_time = models.DateTimeField(blank=True, null=True)
    rating = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_album'


class TArticle(models.Model):
    id = models.IntegerField(primary_key=True)
    thumbnail_url = models.CharField(max_length=100, blank=True, null=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    publish_date = models.DateTimeField(blank=True, null=True)
    teacher = models.ForeignKey('TTeacher', models.DO_NOTHING, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    pic_urls = models.CharField(max_length=100, blank=True, null=True)
    article_category = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_article'


class TAudioChapter(models.Model):
    chapter_name = models.CharField(max_length=50, blank=True, null=True)
    audio_size = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    audio_duration = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)
    audio_url = models.CharField(max_length=100, blank=True, null=True)
    audio = models.ForeignKey(TAlbum, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_audio_chapter'


class TSlidpic(models.Model):
    url = models.ImageField(upload_to='slidpic')
    title = models.CharField(max_length=50, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    upload_time = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    class Meta:
        managed = False
        db_table = 't_slidpic'


class TTask(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    user = models.ForeignKey('TUser', models.DO_NOTHING, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    task_category = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_task'


class TTaskCounter(models.Model):
    count = models.IntegerField(blank=True, null=True)
    name = models.CharField(max_length=20, blank=True, null=True)
    crate_date = models.DateTimeField(blank=True, null=True)
    task = models.ForeignKey(TTask, models.DO_NOTHING, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_task_counter'


class TTeacher(models.Model):
    thumbnail = models.CharField(max_length=50, blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_teacher'


class TUser(models.Model):
    user_id = models.IntegerField(primary_key=True)
    username = models.CharField(max_length=50, blank=True, null=True)
    password = models.CharField(max_length=50, blank=True, null=True)
    thumbnail_url = models.CharField(max_length=100, blank=True, null=True)
    user_info = models.CharField(max_length=100, blank=True, null=True)
    nickname = models.CharField(max_length=50, blank=True, null=True)
    gender = models.IntegerField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    address = models.CharField(max_length=30, blank=True, null=True)
    status = models.IntegerField(blank=True, null=True)
    salt = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 't_user'

main/views.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse
from redis import Redis
from hjs_cmfz import settings
from utils.send_mess import yunpian
# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from utils import random_number
from utils import send_mess
import re


def main(request):
    return render(request, "main.html")


def login_form(request):
    return render(request, "login.html")


redis = Redis(host='localhost', port=6379)
@csrf_exempt
def get_code(request):
    mobile = request.POST.get("mobile")
    print(mobile)
    if mobile:
        value = redis.get(f'{mobile}_1')
        print(value)
        if value:
            return JsonResponse({'status': 0, 'msg': '验证码已发送'})
        code = send_mess.d
        print(code)
        yun = yunpian(settings.APIKEY)
        # yun.send_message(mobile, code)
        redis.set(f"{mobile}_1", code, 60)
        redis.set(f"{mobile}_2", code, 60)
        return JsonResponse({'status': 1, 'msg': '发送成功!'})
    else:
        return JsonResponse({'status': 0, 'msg': '请输入合法的手机号！'})


def check_user(request):
    mobile = request.GET.get("mobile")
    name = request.GET.get("name")
    code = request.GET.get("code")
    print(mobile, name, code, "111111111")
    mobile_check = re.match(r"^1[35678]\d{9}$", mobile)
    code_check = re.match(r"\d{6}$", code)
    if mobile_check and code_check:
        try:
            save_code = redis.get(f'{mobile}_2')
            print(save_code, "2231313")
            if save_code.decode() == code:
                print("111")
                return JsonResponse({'status': 1, 'msg': '登陆成功！'})
        except BaseException as error:
            print(error)
            return JsonResponse({'status': 0, 'msg': f'{error}请发送验证码！'})
        return JsonResponse({'status': 0, 'msg': '登陆失败！'})
    else:
        return JsonResponse({'status': 0, 'msg': '输入不合法'})

templates/echarts.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'echarts/echarts.min.js' %}"></script>
    <script src="{% static 'echarts/china.js' %}"></script>
</head>
<body>
<!-- 为 ECharts 准备一个具备大小（宽高）的 DOM -->
<div id="main" style="width: 600px;height:400px;"></div>
<script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));

    // 指定图表的配置项和数据
    var option = {
        title: {
            text: 'ECharts 入门示例'
        },
        tooltip: {},
        legend: {
            data: ['销量1', '销量2']
        },
        xAxis: {
            data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
        },
        yAxis: {},
        series: [{
            name: '销量',
            type: 'bar',
            data: [5, 20, 36, 10, 10, 20]
        },{
            name: '销量',
            type: 'line',
            data: [5, 20, 36, 10, 10, 20]
        }]
    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
</script>
</body>
</html>

templates/kindeditor.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
    <script src="{% static 'kindeditor/lang/zh-CN.js' %}"></script>
    <script>
        KindEditor.ready(function (K) {
            K.create('#editor_id',{
                width: "800px",
                height: "400px",
                resizeType: 0,
                uploadJson: "/article/upload/",
                allowFileManager: true,     // 显示图片空间的按钮
                fileManagerJson: "/article/get_all_img/",
            });
        });
    </script>
</head>
<body>

<textarea id="editor_id" name="content" style="width:700px;height:300px;">

</textarea>

</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>商品后台管理系统</title>
    <link rel="stylesheet" href="{% static 'boot/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/trirand/ui.jqgrid-bootstrap.css' %}">
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'boot/js/bootstrap.min.js' %}"></script>

    <!--发送按钮倒计时代码-->
    <script type="text/javascript">


        var countdown = 60;

        function settime(obj) {
            if (countdown == 0) {
                obj.removeAttribute("disabled");
                obj.value = "免费获取验证码";
                countdown = 60;
                return;
            } else {
                obj.setAttribute("disabled", true);
                obj.value = "重新发送(" + countdown + ")";
                countdown--;
            }
            setTimeout(function () {
                    settime(obj)
                }
                , 1000)
        }

        $(function () {
            $("#forcode").click(function () {
                let phone = check_phone();
                if (phone) {
                    // 根据用户输入的手机号发送验证码
                    $.ajax({
                        type: 'post',
                        data: {mobile: phone},
                        url: "{% url 'get_code' %}",
                        success: function (data) {
                            console.log(data.status);
                            if (data.status === 1) {
                                alert(data.msg)
                            } else {
                                alert(data.msg)
                            }
                        }
                    });
                } else {
                    alert("请输入合法的手机号！")
                }
            });
            // 验证表单数据是否合法
        $("#loginButtonId").click(function () {
            let check_p = check_phone();
            let check_c = check_code();
            // 如果两项输入都合法则发送请求
            if (check_p && check_c) {
                $.ajax({
                    url: "{% url 'check_user' %}",
                    datatype: 'json',
                    type: 'get',
                    // 获取id为loginForm的表单数据
                    data: $("#loginForm").serialize(),
                    success: function (data) {
                        if (data.status === 1) {
                            location.href = '{% url 'main' %}'

                        } else {
                            alert(data.msg)
                        }
                    }
                });
            } else {
                alert('输入不合法')
            }
        });
        });
        // 检查手机号是否合法
        $("#mobile").blur(function () {
            check_phone()
        });
        // 检查验证码是否合法
        $("#basic-url").blur(function () {
            check_code()
        });

        // 输入手机号正则匹配
        function check_phone() {
            // 获取输入的手机号
            let phone = $("#mobile").val();
            // 手机号提示信息
            let phone_msg = $("#phone_msg");
            // 正则表达式判断
            let phone_re = /^1[3-578]\d{9}$/;
            if (phone_re.test(phone)) {
                phone_msg.html('√');
                return phone
            } else {
                phone_msg.html('×');
                return false
            }
        }

        // 输入验证码正则匹配
        function check_code() {
            let code = $("#basic-url").val();
            let code_msg = $("#code_msg");
            // 正则表达式判断
            let code_re = /\d{6}$/;
            if (code_re.test(code)) {
                code_msg.html('验证码输入合法');
                code_msg.css('color', 'green');
                return code
            } else {
                code_msg.html('请输入合法验证码！');
                code_msg.css('color', 'red');
                return false
            }
        }






    </script>

</head>


<body>

<!--手机号码输入框代码-->
<div class="container">
    <div class="form-group">
        <div class="col-lg-10">
            <form id="loginForm" role="form" action="" method="post" class="form-horizontal">

                <label for="mobile" class="">手机号码:</label>
                <div class="input-group m-bot15" style="width: 400px">
                    <input type="text" maxlength='11' class="form-control" required id="mobile" name="mobile"
                           placeholder="手机号码">
                    <span class="input-group-btn">
                         <input type="button" id="forcode" onclick="settime(this)" value="免费获取验证码"
                                class="btn btn-success">
                    </span>
                </div>
                <span id="msgDiv"></span>
                <p class="help-block" id="phone_msg">请填写绑定手机号</p>
                <label for="basic-url" class="">验证码：</label>
                <div class="input-group">
                    <input type="text" maxlength="6" class="form-control" id="basic-url" required name="code">
                </div>
                <p class="help-block" id="code_msg">请填写接收的验证码</p>

                <p class="help-block"></p>
                <div class="input-group">
                    <input class="btn btn-success" type="button" id="loginButtonId" value="登录">
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>

templates/login1.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>商品后台管理系统</title>
    <link rel="stylesheet" href="{% static 'boot/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/trirand/ui.jqgrid-bootstrap.css' %}">
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'boot/js/bootstrap.min.js' %}"></script>

    <!--发送按钮倒计时代码-->
    <script type="text/javascript">


        var countdown = 60;

        function settime(obj) {
            if (countdown == 0) {
                obj.removeAttribute("disabled");
                obj.value = "免费获取验证码";
                countdown = 60;
                return;
            } else {
                obj.setAttribute("disabled", true);
                obj.value = "重新发送(" + countdown + ")";
                countdown--;
            }
            setTimeout(function () {
                    settime(obj)
                }
                , 1000)
        }

        $(function () {
            $("#forcode").click(function () {
                $.ajax({
                    type: 'post',
                    data: {mobile: $("#mobile").val()},
                    url: "/main/get_code",
                    success: function (data) {
                        console.log(data.status);
                        if (data.status === 1) {
                            alert(data.msg)
                        } else {
                            alert(data.msg)
                        }
                    }
                });

                // 根据用户输入的手机号发送验证码
            });
        })
            // 检查验证码是否合法



    </script>

</head>


<body>

<!--手机号码输入框代码-->
<div class="container">
    <div class="form-group">
        <div class="col-lg-10">
            <form id="loginForm" role="form" action="" method="post" class="form-horizontal">

                <label for="mobile" class="">手机号码:</label>
                <div class="input-group m-bot15">
                    <input type="text" class="form-control" required id="mobile" name="mobile" placeholder="手机号码">
                    <span class="input-group-btn">
                         <input type="button" id="forcode" onclick="settime(this)" value="免费获取验证码"
                                class="btn btn-success">
                        </span>
                </div>
                <span id="msgDiv"></span>
                <p class="help-block">请填写绑定手机号</p>
                <label for="basic-url" class="">用户名</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="basic-url" minlength="5" name="name" required>
                    <span class="input-group-addon">没啥用</span>
                </div>
                <label for="basic-url" class="">验证码：</label>
                <div class="input-group">
                    <input type="text" class="form-control" id="basic-url" required name="code">
                </div>
                <p class="help-block"></p>
                <div class="input-group">
                    <input class="btn btn-success" type="button" id="loginButtonId" value="登录">
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>

templates/login_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>持名法州后台管理系统登陆</title>
    <link rel="stylesheet" href="{% static 'boot/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/css/trirand/ui.jqgrid-bootstrap.css' %}">
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'boot/js/bootstrap.min.js' %}"></script>
</head>
<body>
<br><br><br>
<div class="container">
    <div class="form-group">
        <div class="col-lg-10">
            <form id="loginForm" role="form" action="{% url 'rbac:check_user' %}" method="post" class="form-horizontal">
                {% csrf_token %}
                <label for="mobile" class="">用户名:</label>
                <div class="input-group m-bot15" style="width: 300px">
                    <input type="text" class="form-control" required id="username" name="username">

                </div>
                <br>
                <label for="basic-url" class="">密码：</label>
                <div class="input-group" style="width: 300px">
                    <input type="password" class="form-control" required id="password" name="password">
                </div>
                <br>
                <div class="input-group">
                    <button type="submit" class="btn btn-success" id="loginButtonId" value="登录" onclick="check_username()">登陆</button>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function check_username() {
        $.ajax({
            type: "POST",
            url: "{% url "rbac:check_user" %}",
            data: $("#loginForm").serialize(),
            success: function (data) {
                if (data.status === 1) {
                    location.href = '{% url 'home_index' %}'
                } else {
                    alert(data.msg);
                    location.reload()
                }
            }
        });

    }
</script>
</body>
</html>

templates/map.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>ECharts</title>
    <!-- 引入 echarts.js -->
    <script src="{% static 'echarts/echarts.min.js' %}"></script>
    <script src="{% static 'echarts/china.js' %}"></script>
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
</head>
<body>
<!-- 为ECharts准备一个具备大小（宽高）的Dom -->
<div id="main" style="width: 600px;height:400px;"></div>
<script type="text/javascript">
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));

    // 指定图表的配置项和数据
    var option = {
        title: {
            text: '全国用户分布图',
            subtext: '纯属虚构',
            left: 'center'
        },
        tooltip: {
            trigger: 'item'
        },
        legend: {
            orient: 'vertical',
            left: 'left',
            data: ['1月']
        },
        visualMap: {
            min: 0,
            max: 200,
            left: 'left',
            top: 'bottom',
            text: ['高', '低'],           // 文本，默认为数值文本
            calculable: true
        },
        toolbox: {
            show: true,
            orient: 'vertical',
            left: 'right',
            top: 'center',
            feature: {
                mark: {show: true},
                dataView: {show: true, readOnly: false},
                restore: {show: true},
                saveAsImage: {show: true}
            }
        },
        series: [
            {
                name: '1月',
                type: 'map',
                mapType: 'china',
                roam: false,
                label: {
                    normal: {
                        show: false
                    },
                    emphasis: {
                        show: true
                    }
                },
                data: []
            },
        ]
    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
    // 发送ajax
    $.ajax({
        url: "/user/get_map/",
        datatype: 'json',
        type: 'get',
        success: function (data) {
            myChart.setOption({
                series: [
                    {
                        name: '1月',
                        type: 'map',
                        mapType: 'china',
                        roam: false,
                        label: {
                            normal: {
                                show: false
                            },
                            emphasis: {
                                show: true
                            }
                        },
                        data: data
                    },
                ]
            })
        }
    })
</script>
</body>
</html>